# Generated by Django 4.0.1 on 2022-01-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fuck',
        ),
    ]
