# Generated by Django 4.0.1 on 2022-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank='True', null='True', related_name='+', to='social.Comment'),
            preserve_default='True',
        ),
    ]
