# Generated by Django 4.0.1 on 2022-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_comment_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_level',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
