# Generated by Django 4.0.4 on 2022-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default_weuid3.png', upload_to='uploads/profile_pictures'),
        ),
    ]
